use_frameworks!

platform :ios, '8.0'

target 'TakeTPhoneInfo_Example' do
  pod 'TakeTPhoneInfo', :path => '../'

  target 'TakeTPhoneInfo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
